//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc3_Student3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcdbEntities : DbContext
    {
        public MvcdbEntities()
            : base("name=MvcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb2_class> tb2_class { get; set; }
        public virtual DbSet<tb2_mapping> tb2_mapping { get; set; }
        public virtual DbSet<tb2_student> tb2_student { get; set; }
        public virtual DbSet<tb2_subject> tb2_subject { get; set; }
    }
}
